name: Deploy to GH pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install Packages
        run: yarn install
      # - name: Deploy to GH Pages
      #   run: |
      #     git config --global user.email "bot@example.com"
      #     git config --global user.name ${{secrets.GH_USERNAME}}
      #     git remote set-url origin https://${{secrets.GH_PAT}}@github.com/ssi-anik/github-action-test.git
      #     yarn run build
      #     yarn run deploy
      - name: Build project
        run: yarn run build
      - name: Deploy files to ftp
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ${{ secrets.FTP_UPLOAD_DIR }}

